server:
  port: 9095
spring:
  application:
    name: springboot-rocketmq


###################### rocketMQ ###########################
##http://blog.csdn.net/hxpjava1/article/details/73718355
app:
  rocketmq:
    producer:
      # 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
      groupName: vehicleProducerGroup
      #mq的nameserver地址
      namesrvAddr: 127.0.0.1:9876
      #如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
      instanceName: vehicleProducer
      #topic名称
      topic: vehicleProducerTest
      #根据实际情况设置消息的tag
      tag: vehicleProducerTest
      #消息最大长度
      maxMessageSize: 131072 # 1024*128
      #发送消息超时时间
      sendMsgTimeout: 10000
    consumer:
      namesrvAddr: 127.0.0.1:9876
      groupName: vehicleProducerGroup
      topic: TEST
      tag: TEST
      consumeThreadMin: 20
      consumeThreadMax: 64



### cd Users/sunkaixiang/Downloads/rocketmq-all-4.2.0-bin-release
### Start Name Server  nohup sh bin/mqnamesrv &
### Start Broker nohup sh bin/mqbroker -n localhost:9876 &
###  ps -ef|grep java

### cd /Users/sunkaixiang/IdeaProjects/rocketmq-externals/rocketmq-console
### java -jar target/rocketmq-console-ng-1.0.0.jar